# Generated by Django 3.0.7 on 2020-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
            ],
        ),
    ]
